version: '3.8'

services:
   img_service:
      container_name: learning-go
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 8080:8080
      volumes:
         - ./:/usr/src/app
